### ISSUE TITLE
Importing save files (Steam)

### ISSUE THREAD

**Issue by mvaneijgen** [v-atamanenko/baba-is-you-vita#10]
Maybe this seems out of left field, but I've played Baba is you via Steam the most but not finished it. It seems like the perfect fit on a Vita! So I was looking for a way to move my save file over. 

I've found the following files in my Steam account (https://store.steampowered.com/account/remotestorageapp/?appid=736260)

Baba Is You/Oba.ba
Baba Is _You/Oba.ba.tmp
Baba Is You/ba.ba
Baba Is You/ba.ba.tmp
Baba_Is_You/SettingsC.txt
Baba_Is_You/SettingsC.txt.tmp

If this is not the place to ask, just close this issue.

**Comment by v-atamanenko** [comment]
You can try to remove the following files (if they exist): `ux0:data/baba/assets/0ba.ba`, `ux0:data/baba/assets/2ba.ba`, `ux0:data/baba/assets/ba.ba`, `ux0:data/baba/assets/SettingsC.txt` (don't forget to backup if you still need them) and place the ones you found on your PC in that directory instead.

But I'm 85% sure it won't work, afaik Baba Is You has different set of levels on PC and Android.
