### ISSUE TITLE
Port is not compatible with the last update on Google Play

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [v-atamanenko/baba-is-you-vita#7]
The recent v179 Baba Is You update downloaded to my Android phone as a split APK. Google offers split APKs to reduce download/installation size. The splits typically consist of the base APK that all devices will use (assets and whatnot), an APK for the language of the install device, an APK for the CPU/SOC architecture of the install device (libraries), and an APK for the screen dimensions/resolution/DPI of the install device (launcher icon?, screen DPI).

The previous (un-split/monolithic) version of Baba is You I installed on my Vita includes libraries for ARM64v8, ARMv7, X86, and X86_64 for the hardware architectures. Everything works fine this way, even if the non-ARMv7 architectures are included since I do not think they ever get used. They may be wasting some storage space though.

To get to the installation complications, my current phone is 64-bit so only the split APK with the ARM64v8 libraries ever gets downloaded. I can probably get around this by digging out my older 32-bit phone and downloading the Baba Is You split APKs that way. The README will need to specify that a 32-bit Android device is necessary to download the ARMv7 libraries.

Since the APKs are split, we will need to determine which are necessary. At the minimum the base.apk and the ARMv7 apk will be needed. I assume the language APK will be necessary. I am not sure if the xxxhdpi.apk is needed. The xxxhdpi.apk I pulled from my phone is only 12.4KB. I think it is probably safe just to include all of the split APKs for 32-bit ARMv7 devices. I think that it may be okay to just unzip all the APKs to the same `ux0:data/baba` directory.

I am going to back up my `ux0:data/baba`, and test if unzipping all the 32-bit APK splits into `ux0:data/baba` works okay.

**Comment by DerVerruckteFuchs** [comment]
Update:
My 64-bit phone uses xxxhdpi.apk, my 32-bit phone only uses xxhdpi.apk. The DPI difference from [here](https://iconhandbook.co.uk/reference/chart/android/) shows that xxxhdpi is 640 DPI and xxhdpi is 480 DPI. The Vita is 220 DPI, so the difference may not matter much. If desired, one could use the xxxhdpi.api. I think I'll try that first to see if it works.

**Comment by v-atamanenko** [comment]
I'm working on an update to support the new version, as well as new install instructions. Please stay tuned :)

**Comment by DerVerruckteFuchs** [comment]
@v-atamanenko does v1.3 not work with the updated version of Baba? I can hold off on testing if a new beta/release is needed.

**Comment by v-atamanenko** [comment]
@DerVerruckteFuchs nope, crashes

**Comment by DerVerruckteFuchs** [comment]
I'll hold off then.

**Comment by v-atamanenko** [comment]
@Joach11 @DerVerruckteFuchs fixed in latest build.
