### ISSUE TITLE
The game requires a folder thats not on the .apk

### ISSUE THREAD

**Issue by Joach11** [v-atamanenko/baba-is-you-vita#8]
When I try to boot the game its says that it cant load ux0:data/baba/lib/armeabiv7a/libChowden.so, but there is no "lib" folder on the apk .zip.

**Comment by v-atamanenko** [comment]
@Joach11 port is not ready yet for the fresh google play update. either use previous version or wait a bit till I make a compatibility update https://github.com/v-atamanenko/baba-is-you-vita/issues/7
